/* psy_trials_pin_gen.c - prints tests/adapt/psy_trials_pins.h: the hash of
 * every scripted session of psy_trials_pins_run.h, for the psy_trials.h on
 * the include path. Run it against the version whose behavior is to be
 * pinned (v0.1.1 for the current pins):
 *
 *     git show <rev>:psy_trials.h > /tmp/old/psy_trials.h
 *     gcc -std=c11 -O2 -I/tmp/old -Itests/adapt -o pin_gen tests/adapt/psy_trials_pin_gen.c
 *     ./pin_gen > tests/adapt/psy_trials_pins.h
 *
 * Built with -DPIN_V02 against a v0.2 header (psy_table.h beside it), it
 * prints tests/adapt/psy_trials_pins_v02.h instead, from the designs of
 * psy_trials_pins_v02_run.h (v0.2.0 for the current pins).
 *
 * The pins hold only at the default PSYTR_MAX_TRIALS (4096). */
#define PSY_TRIALS_IMPLEMENTATION
#include "psy_trials.h"

#include <stdio.h>
#include "psy_trials_pins_run.h"
#if defined(PIN_V02)
#include "psy_trials_pins_v02_run.h"
#define GEN_FILE    "psy_trials_pins_v02.h"
#define GEN_RUNNER  "psy_trials_pins_v02_run.h"
#define GEN_N       PIN2_N_DESIGNS
#define GEN_ARRAY   "pin2_want"
#define GEN_COUNT   "PIN2_N_DESIGNS"
#define GEN_VERSION "PIN2_VERSION"
#define GEN_RUN     pin2_run
#else
#define GEN_FILE    "psy_trials_pins.h"
#define GEN_RUNNER  "psy_trials_pins_run.h"
#define GEN_N       PIN_N_DESIGNS
#define GEN_ARRAY   "pin_want"
#define GEN_COUNT   "PIN_N_DESIGNS"
#define GEN_VERSION "PIN_VERSION"
#define GEN_RUN     pin_run
#endif

int main(void) {
    int k, s;
#if defined(PIN_V02)
    (void)pin_run;
#endif
    printf("/* %s - generated by psy_trials_pin_gen.c against psy_trials.h %s.\n"
           " * %s[design][seed]: the hash of each scripted session of\n"
           " * %s. Do not edit; regenerate. */\n", GEN_FILE, psytr_version(), GEN_ARRAY, GEN_RUNNER);
    printf("#define %s \"%s\"\n", GEN_VERSION, psytr_version());
    printf("static const uint64_t %s[%s][PIN_N_SEEDS] = {\n", GEN_ARRAY, GEN_COUNT);
    for (k = 0; k < GEN_N; k++) {
        printf("    {");
        for (s = 0; s < PIN_N_SEEDS; s++)
            printf("%s0x%016llxULL", s ? (s % 3 == 0 ? ",\n     " : ", ") : "", (unsigned long long)GEN_RUN(k, s));
        printf("},\n");
    }
    printf("};\n");
    return 0;
}
