/* psy_trials_pin_gen.c - prints tests/adapt/psy_trials_pins.h: the hash of
 * every scripted session of psy_trials_pins_run.h, for the psy_trials.h on
 * the include path. Run it against the version whose behavior is to be
 * pinned (v0.1.1 for the current pins):
 *
 *     git show <rev>:psy_trials.h > /tmp/old/psy_trials.h
 *     gcc -std=c11 -O2 -I/tmp/old -Itests/adapt -o pin_gen tests/adapt/psy_trials_pin_gen.c
 *     ./pin_gen > tests/adapt/psy_trials_pins.h
 *
 * The pins hold only at the default PSYTR_MAX_TRIALS (4096). */
#define PSY_TRIALS_IMPLEMENTATION
#include "psy_trials.h"

#include <stdio.h>
#include "psy_trials_pins_run.h"

int main(void) {
    int k, s;
    printf("/* psy_trials_pins.h - generated by psy_trials_pin_gen.c against psy_trials.h %s.\n"
           " * pin_want[design][seed]: the hash of each scripted session of\n"
           " * psy_trials_pins_run.h. Do not edit; regenerate. */\n", psytr_version());
    printf("#define PIN_VERSION \"%s\"\n", psytr_version());
    printf("static const uint64_t pin_want[PIN_N_DESIGNS][PIN_N_SEEDS] = {\n");
    for (k = 0; k < PIN_N_DESIGNS; k++) {
        printf("    {");
        for (s = 0; s < PIN_N_SEEDS; s++)
            printf("%s0x%016llxULL", s ? (s % 3 == 0 ? ",\n     " : ", ") : "", (unsigned long long)pin_run(k, s));
        printf("},\n");
    }
    printf("};\n");
    return 0;
}
